use_frameworks!

platform :ios, '8.0'

target 'AdjustAdobeExtension_Example' do
  pod 'AdjustAdobeExtension', :path => '../'

  target 'AdjustAdobeExtension_Tests' do
    inherit! :search_paths

    
  end
end
