use_frameworks!

platform :ios, '10.0'

target 'AdjustAdobeExtension_Example' do
  pod 'AdjustAdobeExtension', :path => '../'
  pod 'ACPGriffon', '~> 1.0'
  pod 'ACPCore', '~> 2.0'
  pod 'ACPUserProfile', '~> 2.0'

  target 'AdjustAdobeExtension_Tests' do
    inherit! :search_paths
  end
end
